#!/usr/bin/env bash
#
# Install this Vim configuration by symlinking it into $HOME.
#
# Safe to re-run: existing correct symlinks are left alone, and any real file
# already at a target path is moved aside to <name>.backup.<timestamp> rather
# than overwritten. Nothing is ever deleted.
#
# Symlinks (not copies) are the point: the installed config stays inside the
# git checkout, so `git pull` updates every machine and `git diff` shows local
# tweaks. Copying or moving files out of the repo severs that.
#
# Usage:
#   ./install.sh            install
#   ./install.sh --dry-run  print what would happen, change nothing
#
set -euo pipefail

REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
STAMP="$(date +%Y%m%d%H%M%S)"
DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

say()  { printf '  %s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
run()  { if (( DRY_RUN )); then say "would: $*"; else "$@"; fi; }

# --- link SRC -> DEST, backing up whatever is in the way ----------------------
link() {
  local src="$1" dest="$2"

  if [[ ! -e "$src" ]]; then
    say "skip $dest (missing in repo: $src)"
    return
  fi

  # Already pointing where we want? Nothing to do.
  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    say "ok   $dest -> $src"
    return
  fi

  # A real file/dir, or a symlink somewhere else: move it aside.
  if [[ -e "$dest" || -L "$dest" ]]; then
    say "back $dest -> $dest.backup.$STAMP"
    run mv -- "$dest" "$dest.backup.$STAMP"
  fi

  say "link $dest -> $src"
  run ln -sfn -- "$src" "$dest"
}

step "Installing from $REPO"
(( DRY_RUN )) && say "(dry run — nothing will change)"

# --- 1. Vim ------------------------------------------------------------------
step "Vim"
run mkdir -p -- "$HOME/.vim"
link "$REPO/.vimrc" "$HOME/.vimrc"

# .vim/ is linked file-by-file rather than as a whole directory, because
# vim-plug writes plugged/ and autoload/plug.vim into it and those must stay
# out of the repo.
if [[ -d "$REPO/.vim" ]]; then
  shopt -s nullglob dotglob
  for item in "$REPO"/.vim/*; do
    link "$item" "$HOME/.vim/$(basename -- "$item")"
  done
  shopt -u nullglob dotglob
fi

# --- 2. Neovim ---------------------------------------------------------------
# Neovim reads ~/.config/nvim/init.vim, not ~/.vimrc. Point it at the same file
# so there is one config to maintain. The .vimrc resolves stdpath('config')
# itself, so vim-plug installs into ~/.config/nvim/plugged there.
step "Neovim"
if command -v nvim >/dev/null 2>&1; then
  run mkdir -p -- "${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
  link "$REPO/.vimrc" "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/init.vim"
else
  say "skip (nvim not installed)"
fi

# --- 3. Machine-local overrides ----------------------------------------------
# Written, not linked: this file is per-machine and must never be committed.
# Only the generated block is rewritten; anything you add below it is kept.
step "Machine-local overrides (~/.vim/local.vim)"
LOCAL="$HOME/.vim/local.vim"
MARK='" ---- end of install.sh generated block ----'

# Does a patched (Powerline/Nerd) font exist? Without one, airline's separator
# glyphs render as tofu boxes, so this decides a vimrc setting.
have_patched_font() {
  local dirs=("$HOME/Library/Fonts" "/Library/Fonts" "$HOME/.local/share/fonts" "$HOME/.fonts" "/usr/share/fonts")
  local d
  for d in "${dirs[@]}"; do
    [[ -d "$d" ]] || continue
    if find "$d" -iname '*nerd*' -o -iname '*powerline*' 2>/dev/null | read -r _; then
      return 0
    fi
  done
  return 1
}

if have_patched_font; then
  POWERLINE=1; say "patched font found — enabling Powerline glyphs"
else
  POWERLINE=0; say "no patched font found — keeping ASCII statusline"
fi

generated_block() {
  cat <<EOF
" Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S') — regenerated on each run.
" Put your own machine-local settings BELOW the marker line; they are preserved.
let g:airline_powerline_fonts = $POWERLINE
let g:airline_symbols_ascii = $(( POWERLINE ? 0 : 1 ))
$MARK
EOF
}

if (( DRY_RUN )); then
  say "would write $LOCAL (airline_powerline_fonts = $POWERLINE)"
else
  if [[ -f "$LOCAL" ]] && grep -qF "$MARK" "$LOCAL"; then
    # Preserve everything the user added after the marker.
    tmp="$(mktemp)"
    generated_block               >  "$tmp"
    sed -n "/$(printf '%s' "$MARK" | sed 's/[][\.*^$/]/\\&/g')/,\$p" "$LOCAL" | tail -n +2 >> "$tmp"
    mv -- "$tmp" "$LOCAL"
    say "updated $LOCAL (your additions kept)"
  elif [[ -f "$LOCAL" ]]; then
    say "back $LOCAL -> $LOCAL.backup.$STAMP"
    mv -- "$LOCAL" "$LOCAL.backup.$STAMP"
    generated_block > "$LOCAL"
    say "wrote $LOCAL"
  else
    generated_block > "$LOCAL"
    say "wrote $LOCAL"
  fi
fi

# --- 4. Optional extras ------------------------------------------------------
step "Optional extras (not installed automatically)"
if ! have_patched_font; then
  if [[ "$(uname -s)" == "Darwin" ]]; then
    say "font:  brew install --cask font-meslo-lg-nerd-font"
  else
    say "font:  sudo apt-get install fonts-powerline   # or your distro's equivalent"
  fi
  say "       then point your terminal at it and re-run this script"
fi
command -v cscope   >/dev/null 2>&1 || say "cscope: not installed (the cscope mappings stay disabled)"
command -v ctags    >/dev/null 2>&1 || say "ctags:  not installed (tag jumping will not work)"
command -v go       >/dev/null 2>&1 || say "go:     not installed (vim-go stays disabled)"
command -v flake8   >/dev/null 2>&1 || say "flake8: not installed (vim-flake8 stays disabled)"

# --- 5. Plugins --------------------------------------------------------------
step "Plugins"
if (( DRY_RUN )); then
  say "would run: vim +PlugInstall +qall"
else
  # The .vimrc bootstraps vim-plug itself on first launch, then this installs
  # the plugins. --sync makes it block; PlugInstall alone would return before
  # the clones finish and +qall would kill them.
  if vim +'PlugInstall --sync' +qall >/dev/null 2>&1; then
    say "plugins installed"
  else
    say "vim exited non-zero — run :PlugInstall inside vim to see why"
  fi
fi

step "Done"
say "Open vim and run :checkhealth (nvim) or :PlugStatus (vim) to verify."
